---

- name: Install PHP-FPM
  yum:
    name="{{ php_prefix }}-{{ item }}"
    state="{{ php_package_state }}"
  with_items: "{{ php_fpm_packages }}"

- name: Kill Dead PHP-FPM Pools
  file:
    name="/opt/nexcess/{{ php_prefix }}/root/etc/php-fpm.d/www.conf"
    state="absent"

- name: Install Opcache Config
  template:
    src="php.d/10-opcache.ini.j2"
    dest="/opt/nexcess/{{ php_prefix }}/root/etc"
    owner="root"
    group="root"
    mode"0644"

- name: Install Default PHP-FPM Pools
  template:
    src="php-fpm.d/{{ item }}"
    dest="/opt/nexcess/{{ php_prefix }}/root/etc/php-fpm.d"
    owner="root"
    group="root"
    mode"0644"
  with_items:
    - default.conf.j2

- name: Start + Start-on-boot
  service:
    name="{{ php_prefix }}-php-fpm"
    enabled="yes"
    state="started"
