---

- name: Install PHP-FPM
  yum:
    name="{{ php_prefix }}-{{ item }}"
    state="{{ php_package_state }}"
  with_items: "{{ php_fpm_packages }}"

- name: Kill Dead PHP-FPM Pools
  file:
    name="/etc/opt/remi/{{ php_prefix }}/php-fpm.d/www.conf"
    state="absent"

- name: Install FPM Pools
  template:
    src="pool-template.conf.j2"
    dest="/etc/opt/remi/{{ php_prefix }}/php-fpm.d/{{ item.name }}.conf"
    owner="root"
    group="root"
    mode="0644"
  with_items: "{{ php_fpm_pools }}"

- name: Start-on-boot
  service:
    name="{{ php_prefix }}-php-fpm"
    enabled="yes"
