---

- name: Install PHP
  yum:
    name="{{ php_prefix }}-{{ item }}"
    state="{{ php_package_state }}"
  with_items: "{{ php_base_packages }}"

- name: Install PECL Mods
  yum:
    name="{{ php_prefix }}-{{ item }}"
    state="{{ php_package_state }}"
  with_items: "{{ php_pecl_modules }}"

- name: Install Browscap.INI
  template:
    src="browscap.ini.j2"
    dest="/etc/browscap.ini"
    owner="root"
    group="root"
    mode="0644"
  when: php_install_browscap_ini

- name: Gather SCL Binary List
  find:
    paths="{{ php_root }}/usr/bin"
    recurse="no"
  register: found

- name: Symlink SCL Binaries
  file:
    src="{{ item.path }}"
    dest="/usr/bin/{{ item.path | basename }}"
    owner="root"
    group="root"
    mode="0755"
    state="link"
  with_items: "{{ found.files }}"
  when: php_symlink_scl_bins

- name: Symlink PHP.ini
  file:
    src="{{ php_root }}/etc/php.ini"
    dest="/etc/php.ini"
    owner="root"
    group="root"
    mode="0644"
    state="link"

- name: Setup FPM
  include: "fpm.yml"
  when: php_fpm_enabled
