---
- name: Check For Existing OpCache Config Files.
  find:
    paths="{{ item }}"
    contains="zend_extension(\s+)?=(\s+)?opcache\.so"
  register: php_installed_opcache_confs
  with_items: "{{ php_extension_conf_paths }}"

- name: Remove Any Non-role-supplied OpCache Config Files.
  file:
    path="{{ item.1.path }}"
    state="absent"
  when: php_opcache_conf_filename != (item.1.path.split('/') | last)
  with_subelements:
    - "{{ php_installed_opcache_confs.results }}"
    - "files"
  notify: restart php

- name: Ensure OpCache Config File is Present.
  template:
    src="opcache.ini.j2"
    dest="{{ item }}/{{ php_opcache_conf_filename }}"
    owner="root"
    group="root"
    force="yes"
    mode="0644"
  with_items: "{{ php_extension_conf_paths }}"
  when: php_opcache_enable
  notify: restart php

- name: Remove OpCache Config File if OpCache is Disabled.
  file:
    path="{{ item }}/{{ php_opcache_conf_filename }}"
    state="absent"
  with_items: "{{ php_extension_conf_paths }}"
  when: not php_opcache_enable
  notify: restart php
